name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup libasound2-dev on ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libasound2-dev libopus-dev libortp-dev
      
    - uses: actions/checkout@v2
    - name: make
      run: make
